In [ ]:
import pandas as pd


In [ ]:
df = pd.read_excel("/content/empdata.xlsx")

In [ ]:
df


Empid           Ename    Salary                  DOJ
0   1001          Ganesh   1000.00  2000-10-10 00:00:00
1   1002            Anil  23000.50            3/20/2002
2   1003          Gaurav       NaN  2002-03-03 00:00:00
3   1004    Hema Chandra  16500.50  2000-10-09 00:00:00
4   1005  Laxmi Prasanna  12000.75  2000-08-10 00:00:00
5   1006          Anant    9999.99  1999-09-09 00:00:00

In [ ]:
df.head()

Empid           Ename    Salary                  DOJ
0   1001          Ganesh   1000.00  2000-10-10 00:00:00
1   1002            Anil  23000.50            3/20/2002
2   1003          Gaurav       NaN  2002-03-03 00:00:00
3   1004    Hema Chandra  16500.50  2000-10-09 00:00:00
4   1005  Laxmi Prasanna  12000.75  2000-08-10 00:00:00

In [ ]:
df.tail()

Empid           Ename    Salary                  DOJ
1   1002            Anil  23000.50            3/20/2002
2   1003          Gaurav       NaN  2002-03-03 00:00:00
3   1004    Hema Chandra  16500.50  2000-10-09 00:00:00
4   1005  Laxmi Prasanna  12000.75  2000-08-10 00:00:00
5   1006          Anant    9999.99  1999-09-09 00:00:00

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Empid   6 non-null      int64  
 1   Ename   6 non-null      object 
 2   Salary  5 non-null      float64
 3   DOJ     6 non-null      object 
dtypes: float64(1), int64(1), object(2)
memory usage: 320.0+ bytes


In [ ]:
df.Empid

0    1001
1    1002
2    1003
3    1004
4    1005
5    1006
Name: Empid, dtype: int64

In [ ]:
df.columns

Index(['Empid', 'Ename', 'Salary', 'DOJ'], dtype='object')

In [ ]:
df.describe()

Empid        Salary
count     6.000000      5.000000
mean   1003.500000  12500.348000
std       1.870829   8139.622234
min    1001.000000   1000.000000
25%    1002.250000   9999.990000
50%    1003.500000  12000.750000
75%    1004.750000  16500.500000
max    1006.000000  23000.500000

In [ ]:
df.shape

(6, 4)

In [ ]:
df[["Empid","Salary"]]

Empid    Salary
0   1001   1000.00
1   1002  23000.50
2   1003       NaN
3   1004  16500.50
4   1005  12000.75
5   1006   9999.99

In [ ]:
df.isnull()


Empid  Ename  Salary    DOJ
0  False  False   False  False
1  False  False   False  False
2  False  False    True  False
3  False  False   False  False
4  False  False   False  False
5  False  False   False  False

In [ ]:
df.isnull().sum()


Empid     0
Ename     0
Salary    1
DOJ       0
dtype: int64

In [ ]:
df.dropna(axis=0,inplace=False)

Empid           Ename    Salary                  DOJ
0   1001          Ganesh   1000.00  2000-10-10 00:00:00
1   1002            Anil  23000.50            3/20/2002
3   1004    Hema Chandra  16500.50  2000-10-09 00:00:00
4   1005  Laxmi Prasanna  12000.75  2000-08-10 00:00:00
5   1006          Anant    9999.99  1999-09-09 00:00:00

In [ ]:
df.isnull().sum()

Empid     0
Ename     0
Salary    1
DOJ       0
dtype: int64

In [ ]:
df.dropna(axis=0,inplace=True)
df

Empid           Ename    Salary                  DOJ
0   1001          Ganesh   1000.00  2000-10-10 00:00:00
1   1002            Anil  23000.50            3/20/2002
3   1004    Hema Chandra  16500.50  2000-10-09 00:00:00
4   1005  Laxmi Prasanna  12000.75  2000-08-10 00:00:00
5   1006          Anant    9999.99  1999-09-09 00:00:00

In [ ]:
df["Salary"].max()

23000.5

In [ ]:
df[df.Salary>20000]

Empid Ename   Salary        DOJ
1   1002  Anil  23000.5  3/20/2002

In [ ]:
import numpy as np
A2=np.array([[[1,2,3],[4,5,6],[6,7,8]]])
print(A2)

[[[1 2 3]
  [4 5 6]
  [6 7 8]]]


In [ ]:
A2.ndim

3

In [ ]:
A2.shape


(1, 3, 3)

In [ ]:
Za=np.zeros((3,3),dtype=int)
print(Za)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
Za=np.zeros((2,3,3),dtype=int)

print(Za)


[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [ ]:
aa=np.ones(2,dtype=int)
print(aa)

[1 1]


In [ ]:
aa=np.ones((3,3),dtype=int)
print(aa)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
aaa=np.full(2,3)
print(aaa)

[3 3]


In [ ]:
aaa=np.full([2,3],9)
print(aaa)

In [ ]:
aaa.ndim

1

In [ ]:
q=np.array(aa+A2)
print(q)


[[[2 3 4]
  [5 6 7]
  [7 8 9]]]


In [ ]:
q=np.array(aa-A2)
print(q)


[[[ 0 -1 -2]
  [-3 -4 -5]
  [-5 -6 -7]]]


In [ ]:
q=np.array(aa*A2)
print(q)


[[[1 2 3]
  [4 5 6]
  [6 7 8]]]


In [ ]:
q=np.array(aa/A2)
print(q)


[[[1.         0.5        0.33333333]
  [0.25       0.2        0.16666667]
  [0.16666667 0.14285714 0.125     ]]]


In [ ]:
AB=np.add(aa,aa)
print(AB)

[[2 2 2]
 [2 2 2]
 [2 2 2]]
